package ir.digixo.hellows.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2025-06-23T00:57:47.619+03:30
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://ws.hellows.digixo.ir/", name = "HelloWs")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWs {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.hellows.digixo.ir/", className = "ir.digixo.hellows.ws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.hellows.digixo.ir/", className = "ir.digixo.hellows.ws.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
